spring.application.name=Bookstore
# Default to H2 for easy local dev and cloud hosting
spring.profiles.active=${SPRING_PROFILES_ACTIVE:h2}

# Use the PORT provided by Render, or 8080 locally
server.port=${PORT:8080}

# Allow H2 Console to be accessed in the cloud (for debugging)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true